[package]
name = "lunal-attestation"
version = "0.1.0"
edition = "2024"


[features]
default = []
attestation = ["tdx"]

[dependencies]
clap = "4.0"
dcap-rs = { git = "https://github.com/automata-network/dcap-rs.git" }
hex = "0.4"
tdx = { git = "https://github.com/automata-network/tdx-attestation-sdk", package = "tdx", branch = "main", optional = true }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
urlencoding = "2.1"
flate2 = "1.0"
base64 = "0.13"


[[bin]]
name = "attest"
path = "src/bin/attest.rs"