[workspace]
members = [
    "lunal-attestation",
    "vtpm-attestation",
    "amd-vtpm",
    "amd-vtpm/example"
]
resolver = "2"

[workspace.dependencies]
# Common dependencies shared across workspace members
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = "1.45"
reqwest = { version = "0.12", features = ["json", "blocking"] }
hex = "0.4"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
bincode = "1.3.1"
urlencoding = "2.1"
flate2 = "1.0"

# Dependencies from vtpm-attestation
thiserror = "2.0.3"
sev = { version = "6.2.1", features = ["crypto_nossl"] }
zerocopy = { version = "0.8.26", features = ["derive"] }